accompaniment_states: [NAO_IDENTIFICADO, ANTERIOR, ATIVO, INTENSIVO, PIAAP_ATIVO, ENCAMINHADO, CONCLUIDO, ARTICULACAO]
case_states: [PRIMEIRA_ANALISE, ACOMPANHAMENTO_ATIVO, MONITORAMENTO, REAVALIACAO, PIAAP_ATIVO, ANALISE_POSSIVEL_SUSPENSAO, RECURSO, ENCERRADO]
crps: [CRPS-0, CRPS-1, CRPS-2, CRPS-3]
