from __future__ import annotations
from datetime import datetime, date, timezone
from typing import Optional
from sqlalchemy import String,Integer,Float,Boolean,DateTime,Date,Text,ForeignKey,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from src.db.base import Base

def utcnow():
    """UTC sem timezone para compatibilidade com colunas DateTime existentes."""
    return datetime.now(timezone.utc).replace(tzinfo=None)

class T:
    created_at: Mapped[datetime]=mapped_column(DateTime,default=utcnow,nullable=False)
    updated_at: Mapped[datetime]=mapped_column(DateTime,default=utcnow,onupdate=utcnow,nullable=False)

class Student(Base,T):
    __tablename__='estudantes'; id:Mapped[int]=mapped_column(primary_key=True); grr:Mapped[str]=mapped_column(String(20),unique=True,index=True); nome:Mapped[str]=mapped_column(String(200)); curso:Mapped[Optional[str]]=mapped_column(String(200)); codigo_curso:Mapped[Optional[str]]=mapped_column(String(50)); curriculo:Mapped[Optional[str]]=mapped_column(String(50)); campus:Mapped[Optional[str]]=mapped_column(String(100)); ingresso:Mapped[Optional[str]]=mapped_column(String(20))
class Cycle(Base,T):
    __tablename__='ciclos'; id:Mapped[int]=mapped_column(primary_key=True); codigo:Mapped[str]=mapped_column(String(20),unique=True,index=True); status:Mapped[str]=mapped_column(String(60),default='PREPARACAO_DADOS'); frozen_at:Mapped[Optional[datetime]]=mapped_column(DateTime); hashes_bases:Mapped[Optional[str]]=mapped_column(Text); code_version:Mapped[Optional[str]]=mapped_column(String(50)); mcn_version:Mapped[Optional[str]]=mapped_column(String(50)); ial_version:Mapped[Optional[str]]=mapped_column(String(50)); config_version:Mapped[Optional[str]]=mapped_column(String(50)); responsavel:Mapped[Optional[str]]=mapped_column(String(120))
class Benefit(Base,T):
    __tablename__='beneficios'; id:Mapped[int]=mapped_column(primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('estudantes.id'),index=True); cycle_id:Mapped[int]=mapped_column(ForeignKey('ciclos.id'),index=True); modalidade:Mapped[str]=mapped_column(String(120)); status:Mapped[str]=mapped_column(String(60),default='ATIVO')
class AcademicHistory(Base,T):
    __tablename__='historico_academico'; id:Mapped[int]=mapped_column(primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('estudantes.id'),index=True); periodo:Mapped[str]=mapped_column(String(20),index=True); disciplina_codigo:Mapped[str]=mapped_column(String(60)); disciplina_nome:Mapped[Optional[str]]=mapped_column(String(240)); turma:Mapped[Optional[str]]=mapped_column(String(60)); ch:Mapped[Optional[float]]=mapped_column(Float); obrigatoria:Mapped[Optional[bool]]=mapped_column(Boolean); situacao:Mapped[Optional[str]]=mapped_column(String(80)); aprovado:Mapped[Optional[bool]]=mapped_column(Boolean); rep_nota:Mapped[Optional[bool]]=mapped_column(Boolean); rep_freq:Mapped[Optional[bool]]=mapped_column(Boolean); cancelado:Mapped[Optional[bool]]=mapped_column(Boolean); nota:Mapped[Optional[float]]=mapped_column(Float); frequencia_pct:Mapped[Optional[float]]=mapped_column(Float)
class CurriculumParameter(Base,T):
    __tablename__='parametros_curriculares'; id:Mapped[int]=mapped_column(primary_key=True); codigo_curso:Mapped[str]=mapped_column(String(50),index=True); curriculo:Mapped[str]=mapped_column(String(50),index=True); campus:Mapped[Optional[str]]=mapped_column(String(100)); etapa:Mapped[Optional[str]]=mapped_column(String(50)); duracao_regular_periodos:Mapped[Optional[int]]=mapped_column(Integer); ch_total:Mapped[Optional[float]]=mapped_column(Float); ch_minima_art18:Mapped[Optional[float]]=mapped_column(Float); grau_evidencia:Mapped[str]=mapped_column(String(1),default='D'); fonte:Mapped[Optional[str]]=mapped_column(String(240))
class MandatoryDiscipline(Base,T):
    __tablename__='disciplinas_obrigatorias'; id:Mapped[int]=mapped_column(primary_key=True); codigo_curso:Mapped[str]=mapped_column(String(50),index=True); curriculo:Mapped[str]=mapped_column(String(50),index=True); disciplina_codigo:Mapped[str]=mapped_column(String(60)); disciplina_nome:Mapped[Optional[str]]=mapped_column(String(240)); etapa_recomendada:Mapped[Optional[str]]=mapped_column(String(50))
class ClassApprovalRate(Base,T):
    __tablename__='taxas_aprovacao_turmas'; id:Mapped[int]=mapped_column(primary_key=True); periodo:Mapped[str]=mapped_column(String(20),index=True); disciplina_codigo:Mapped[str]=mapped_column(String(60)); turma:Mapped[Optional[str]]=mapped_column(String(60)); matriculados:Mapped[Optional[int]]=mapped_column(Integer); aprovados:Mapped[Optional[int]]=mapped_column(Integer); taxa_aprovacao_pct:Mapped[Optional[float]]=mapped_column(Float); fonte:Mapped[Optional[str]]=mapped_column(String(240)); validada:Mapped[bool]=mapped_column(Boolean,default=False)
class IntegrationTime(Base,T):
    __tablename__='integralizacao_tempo'; id:Mapped[int]=mapped_column(primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('estudantes.id'),index=True); cycle_id:Mapped[int]=mapped_column(ForeignKey('ciclos.id'),index=True); ch_total:Mapped[Optional[float]]=mapped_column(Float); ch_integralizada:Mapped[Optional[float]]=mapped_column(Float); periodos_vinculo:Mapped[Optional[int]]=mapped_column(Integer); periodos_computaveis:Mapped[Optional[int]]=mapped_column(Integer); periodos_regulares:Mapped[Optional[int]]=mapped_column(Integer); mudanca_curso:Mapped[bool]=mapped_column(Boolean,default=False); retorno:Mapped[bool]=mapped_column(Boolean,default=False); trancamentos:Mapped[Optional[int]]=mapped_column(Integer); processo_academico:Mapped[Optional[str]]=mapped_column(String(120)); poa_plano_estudos:Mapped[Optional[str]]=mapped_column(String(120))
class LegacyAcademicSnapshot(Base,T):
    __tablename__='snapshot_academico_legado'; id:Mapped[int]=mapped_column(primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('estudantes.id'),index=True); cycle_id:Mapped[int]=mapped_column(ForeignKey('ciclos.id'),index=True); source_name:Mapped[Optional[str]]=mapped_column(String(240)); setor:Mapped[Optional[str]]=mapped_column(String(200)); curso:Mapped[Optional[str]]=mapped_column(String(200)); proafe:Mapped[Optional[str]]=mapped_column(String(200)); motivo:Mapped[Optional[str]]=mapped_column(Text); renda_per_capita:Mapped[Optional[float]]=mapped_column(Float); classe_renda:Mapped[Optional[str]]=mapped_column(String(40)); nota_renda:Mapped[Optional[float]]=mapped_column(Float); ano_ingresso:Mapped[Optional[int]]=mapped_column(Integer); tempo_sem:Mapped[Optional[int]]=mapped_column(Integer); ch_integralizada_pct:Mapped[Optional[float]]=mapped_column(Float); ch_ideal:Mapped[Optional[float]]=mapped_column(Float); qtd_matriculada:Mapped[Optional[int]]=mapped_column(Integer); qtd_rep_nota:Mapped[Optional[int]]=mapped_column(Integer); qtd_rep_freq:Mapped[Optional[int]]=mapped_column(Integer); qtd_cancelada:Mapped[Optional[int]]=mapped_column(Integer); ira_sem:Mapped[Optional[float]]=mapped_column(Float); aprovacao_pct:Mapped[Optional[float]]=mapped_column(Float); ch_recomendada_sem:Mapped[Optional[float]]=mapped_column(Float); ch_mat_total:Mapped[Optional[float]]=mapped_column(Float); baixa_mat:Mapped[Optional[str]]=mapped_column(String(120)); hist_rf_1:Mapped[Optional[float]]=mapped_column(Float); hist_rf_2:Mapped[Optional[float]]=mapped_column(Float); hist_rf_3:Mapped[Optional[float]]=mapped_column(Float); hist_rf_media:Mapped[Optional[float]]=mapped_column(Float); avaliacao_anterior:Mapped[Optional[bool]]=mapped_column(Boolean); avaliacao_2024:Mapped[Optional[str]]=mapped_column(String(120)); recebeu_aux_anterior:Mapped[Optional[bool]]=mapped_column(Boolean); legacy_ita:Mapped[Optional[float]]=mapped_column(Float); legacy_classificacao:Mapped[Optional[str]]=mapped_column(String(80)); responsavel_anterior:Mapped[Optional[str]]=mapped_column(String(160)); raw_json:Mapped[Optional[str]]=mapped_column(Text); __table_args__=(UniqueConstraint('student_id','cycle_id',name='uq_snapshot_student_cycle'),)
class LegacyProcessEvent(Base,T):
    __tablename__='eventos_processo_legado'; id:Mapped[int]=mapped_column(primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('estudantes.id'),index=True); cycle_id:Mapped[int]=mapped_column(ForeignKey('ciclos.id'),index=True); source_name:Mapped[Optional[str]]=mapped_column(String(240)); responsavel_2024:Mapped[Optional[str]]=mapped_column(String(160)); responsavel_2025_1:Mapped[Optional[str]]=mapped_column(String(160)); observacoes_1:Mapped[Optional[str]]=mapped_column(Text); parecer_1:Mapped[Optional[str]]=mapped_column(String(200)); situacao_1:Mapped[Optional[str]]=mapped_column(String(120)); respondeu_recurso_final:Mapped[Optional[str]]=mapped_column(String(80)); observacoes_2:Mapped[Optional[str]]=mapped_column(Text); parecer_2:Mapped[Optional[str]]=mapped_column(String(200)); situacao_2:Mapped[Optional[str]]=mapped_column(String(120)); raw_json:Mapped[Optional[str]]=mapped_column(Text); __table_args__=(UniqueConstraint('student_id','cycle_id',name='uq_legacy_process_student_cycle'),)
class MCNResult(Base,T):
    __tablename__='mcn'; id:Mapped[int]=mapped_column(primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('estudantes.id'),index=True); cycle_id:Mapped[int]=mapped_column(ForeignKey('ciclos.id'),index=True); artigo:Mapped[str]=mapped_column(String(10)); status:Mapped[str]=mapped_column(String(40)); evidencia:Mapped[Optional[str]]=mapped_column(Text); fonte:Mapped[Optional[str]]=mapped_column(String(240)); qualidade_dado:Mapped[Optional[str]]=mapped_column(String(60)); requer_conferencia:Mapped[bool]=mapped_column(Boolean,default=False); regra_versao:Mapped[str]=mapped_column(String(50)); __table_args__=(UniqueConstraint('student_id','cycle_id','artigo',name='uq_mcn_student_cycle_art'),)
class IALResult(Base,T):
    __tablename__='ial'; id:Mapped[int]=mapped_column(primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('estudantes.id'),index=True); cycle_id:Mapped[int]=mapped_column(ForeignKey('ciclos.id'),index=True); r:Mapped[Optional[float]]=mapped_column(Float); f:Mapped[Optional[float]]=mapped_column(Float); p:Mapped[Optional[float]]=mapped_column(Float); score:Mapped[Optional[float]]=mapped_column(Float); cobertura:Mapped[float]=mapped_column(Float,default=0); status:Mapped[str]=mapped_column(String(80)); faixa:Mapped[Optional[str]]=mapped_column(String(120)); versao:Mapped[str]=mapped_column(String(50))
class ProtectionFactor(Base,T):
    __tablename__='fatores_protecao'; id:Mapped[int]=mapped_column(primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('estudantes.id'),index=True); cycle_id:Mapped[int]=mapped_column(ForeignKey('ciclos.id'),index=True); fator:Mapped[str]=mapped_column(String(120)); fonte:Mapped[str]=mapped_column(String(60)); status:Mapped[str]=mapped_column(String(80)); data_registro:Mapped[Optional[date]]=mapped_column(Date); status_atualidade:Mapped[Optional[str]]=mapped_column(String(80)); observacao:Mapped[Optional[str]]=mapped_column(Text); pre_analise:Mapped[bool]=mapped_column(Boolean,default=False)
class Accompaniment(Base,T):
    __tablename__='acompanhamentos'; id:Mapped[int]=mapped_column(primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('estudantes.id'),index=True); cycle_id:Mapped[int]=mapped_column(ForeignKey('ciclos.id'),index=True); setor:Mapped[str]=mapped_column(String(100)); estado:Mapped[str]=mapped_column(String(60)); data_ultimo_registro:Mapped[Optional[date]]=mapped_column(Date); fonte:Mapped[Optional[str]]=mapped_column(String(240)); objetivo_sintetico:Mapped[Optional[str]]=mapped_column(Text)
class EvaluationHistory(Base,T):
    __tablename__='historico_avaliacoes'; id:Mapped[int]=mapped_column(primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('estudantes.id'),index=True); ciclo_codigo:Mapped[str]=mapped_column(String(20)); participou:Mapped[bool]=mapped_column(Boolean,default=True); profissional:Mapped[Optional[str]]=mapped_column(String(160)); resultado:Mapped[Optional[str]]=mapped_column(String(120)); fase:Mapped[Optional[str]]=mapped_column(String(80)); mna:Mapped[Optional[str]]=mapped_column(String(120)); piaap:Mapped[bool]=mapped_column(Boolean,default=False); acoes_pactuadas:Mapped[Optional[str]]=mapped_column(Text); ial_anterior:Mapped[Optional[float]]=mapped_column(Float); mcn_resumo:Mapped[Optional[str]]=mapped_column(Text)
class Prioritization(Base,T):
    __tablename__='priorizacoes'; id:Mapped[int]=mapped_column(primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('estudantes.id'),index=True); cycle_id:Mapped[int]=mapped_column(ForeignKey('ciclos.id'),index=True); camada:Mapped[str]=mapped_column(String(10)); ordem_na_camada:Mapped[int]=mapped_column(Integer,default=0); razoes:Mapped[str]=mapped_column(Text); pre_selecionado:Mapped[bool]=mapped_column(Boolean,default=False); validado_equipe:Mapped[bool]=mapped_column(Boolean,default=False); selecionado_final:Mapped[bool]=mapped_column(Boolean,default=False); alteracao_manual:Mapped[bool]=mapped_column(Boolean,default=False); justificativa_manual:Mapped[Optional[str]]=mapped_column(Text)
class Allocation(Base,T):
    __tablename__='distribuicoes'; id:Mapped[int]=mapped_column(primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('estudantes.id'),index=True); cycle_id:Mapped[int]=mapped_column(ForeignKey('ciclos.id'),index=True); profissional_id:Mapped[str]=mapped_column(String(50)); complexidade:Mapped[Optional[str]]=mapped_column(String(40)); motivo_balanceamento:Mapped[Optional[str]]=mapped_column(Text)
class Contextualization(Base,T):
    __tablename__='contextualizacoes'; id:Mapped[int]=mapped_column(primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('estudantes.id'),index=True); cycle_id:Mapped[int]=mapped_column(ForeignKey('ciclos.id'),index=True); tipo:Mapped[str]=mapped_column(String(60)); status:Mapped[str]=mapped_column(String(60),default='PENDENTE'); resposta_json:Mapped[Optional[str]]=mapped_column(Text); data_resposta:Mapped[Optional[datetime]]=mapped_column(DateTime)
class Attendance(Base,T):
    __tablename__='atendimentos'; id:Mapped[int]=mapped_column(primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('estudantes.id'),index=True); cycle_id:Mapped[int]=mapped_column(ForeignKey('ciclos.id'),index=True); profissional_id:Mapped[str]=mapped_column(String(50)); data_atendimento:Mapped[datetime]=mapped_column(DateTime); dados_validados:Mapped[Optional[str]]=mapped_column(Text); novas_barreiras:Mapped[Optional[str]]=mapped_column(Text); sintese:Mapped[Optional[str]]=mapped_column(Text); orientacoes:Mapped[Optional[str]]=mapped_column(Text); encaminhamentos:Mapped[Optional[str]]=mapped_column(Text); indica_mna:Mapped[bool]=mapped_column(Boolean,default=False); indica_piaap:Mapped[bool]=mapped_column(Boolean,default=False); proximo_marco:Mapped[Optional[str]]=mapped_column(String(160))
class MAIC(Base,T):
    __tablename__='maic'; id:Mapped[int]=mapped_column(primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('estudantes.id'),index=True); cycle_id:Mapped[int]=mapped_column(ForeignKey('ciclos.id'),index=True); profissional_id:Mapped[str]=mapped_column(String(50)); dados_objetivos:Mapped[Optional[str]]=mapped_column(Text); analise_profissional:Mapped[Optional[str]]=mapped_column(Text); responsabilidade_institucional:Mapped[Optional[str]]=mapped_column(Text); conclusao:Mapped[Optional[str]]=mapped_column(Text); concluida:Mapped[bool]=mapped_column(Boolean,default=False)
class MNA(Base,T):
    __tablename__='mna'; id:Mapped[int]=mapped_column(primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('estudantes.id'),index=True); cycle_id:Mapped[int]=mapped_column(ForeignKey('ciclos.id'),index=True); modalidade:Mapped[str]=mapped_column(String(120)); intensidade:Mapped[Optional[str]]=mapped_column(String(60)); objetivo:Mapped[Optional[str]]=mapped_column(Text); responsavel:Mapped[Optional[str]]=mapped_column(String(160)); prazo:Mapped[Optional[date]]=mapped_column(Date); justificativa:Mapped[Optional[str]]=mapped_column(Text)
class PIAAP(Base,T):
    __tablename__='piaap'; id:Mapped[int]=mapped_column(primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('estudantes.id'),index=True); cycle_id:Mapped[int]=mapped_column(ForeignKey('ciclos.id'),index=True); objetivo_geral:Mapped[Optional[str]]=mapped_column(Text); status:Mapped[str]=mapped_column(String(60),default='ATIVO'); data_revisao:Mapped[Optional[date]]=mapped_column(Date)
class PIAAPAction(Base,T):
    __tablename__='piaap_acoes'; id:Mapped[int]=mapped_column(primary_key=True); piaap_id:Mapped[int]=mapped_column(ForeignKey('piaap.id'),index=True); tipo:Mapped[str]=mapped_column(String(80)); descricao:Mapped[str]=mapped_column(Text); parte_responsavel:Mapped[str]=mapped_column(String(40)); responsavel:Mapped[Optional[str]]=mapped_column(String(160)); prazo:Mapped[Optional[date]]=mapped_column(Date); indicador:Mapped[Optional[str]]=mapped_column(String(240)); status:Mapped[str]=mapped_column(String(60),default='PENDENTE'); resultado:Mapped[Optional[str]]=mapped_column(Text)
class Maintenance(Base,T):
    __tablename__='manutencoes'; id:Mapped[int]=mapped_column(primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('estudantes.id'),index=True); cycle_id:Mapped[int]=mapped_column(ForeignKey('ciclos.id'),index=True); modalidade:Mapped[str]=mapped_column(String(120)); responsavel:Mapped[str]=mapped_column(String(120)); proximo_marco:Mapped[Optional[str]]=mapped_column(String(160))
class Monitoring(Base,T):
    __tablename__='monitoramentos'; id:Mapped[int]=mapped_column(primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('estudantes.id'),index=True); cycle_id:Mapped[int]=mapped_column(ForeignKey('ciclos.id'),index=True); tipo_parte:Mapped[str]=mapped_column(String(40)); acao:Mapped[str]=mapped_column(Text); responsavel:Mapped[Optional[str]]=mapped_column(String(160)); prazo:Mapped[Optional[date]]=mapped_column(Date); status:Mapped[str]=mapped_column(String(60)); justificativa:Mapped[Optional[str]]=mapped_column(Text); pendencia_institucional:Mapped[bool]=mapped_column(Boolean,default=False)
class Reassessment(Base,T):
    __tablename__='reavaliacoes'; id:Mapped[int]=mapped_column(primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('estudantes.id'),index=True); cycle_id:Mapped[int]=mapped_column(ForeignKey('ciclos.id'),index=True); ciclo_anterior:Mapped[str]=mapped_column(String(20)); comparacao_json:Mapped[Optional[str]]=mapped_column(Text); persistencia_quantitativa:Mapped[Optional[bool]]=mapped_column(Boolean); persistencia_fundamentada:Mapped[Optional[str]]=mapped_column(Text); escuta_realizada:Mapped[bool]=mapped_column(Boolean,default=False)
class CRPS(Base,T):
    __tablename__='crps'; id:Mapped[int]=mapped_column(primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('estudantes.id'),index=True); cycle_id:Mapped[int]=mapped_column(ForeignKey('ciclos.id'),index=True); categoria:Mapped[Optional[str]]=mapped_column(String(20)); checklist_json:Mapped[Optional[str]]=mapped_column(Text); profissional_id:Mapped[Optional[str]]=mapped_column(String(50)); justificativa:Mapped[Optional[str]]=mapped_column(Text)
class Opinion(Base,T):
    __tablename__='pareceres'; id:Mapped[int]=mapped_column(primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('estudantes.id'),index=True); cycle_id:Mapped[int]=mapped_column(ForeignKey('ciclos.id'),index=True); profissional_id:Mapped[str]=mapped_column(String(50)); texto:Mapped[str]=mapped_column(Text); conclusao:Mapped[Optional[str]]=mapped_column(String(160))
class Notification(Base,T):
    __tablename__='notificacoes'; id:Mapped[int]=mapped_column(primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('estudantes.id'),index=True); cycle_id:Mapped[int]=mapped_column(ForeignKey('ciclos.id'),index=True); tipo:Mapped[str]=mapped_column(String(80)); data_envio:Mapped[Optional[datetime]]=mapped_column(DateTime); prazo:Mapped[Optional[date]]=mapped_column(Date); status:Mapped[str]=mapped_column(String(60),default='RASCUNHO')
class Appeal(Base,T):
    __tablename__='recursos'; id:Mapped[int]=mapped_column(primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('estudantes.id'),index=True); cycle_id:Mapped[int]=mapped_column(ForeignKey('ciclos.id'),index=True); etapa:Mapped[str]=mapped_column(String(80)); data_recebimento:Mapped[Optional[datetime]]=mapped_column(DateTime); status:Mapped[str]=mapped_column(String(60)); texto:Mapped[Optional[str]]=mapped_column(Text); decisao:Mapped[Optional[str]]=mapped_column(Text); prazo:Mapped[Optional[date]]=mapped_column(Date)
class CommissionEvent(Base,T):
    __tablename__='comissao_eventos'; id:Mapped[int]=mapped_column(primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('estudantes.id'),index=True); cycle_id:Mapped[int]=mapped_column(ForeignKey('ciclos.id'),index=True); evento:Mapped[str]=mapped_column(String(120)); data_evento:Mapped[datetime]=mapped_column(DateTime); resumo_minimizado:Mapped[Optional[str]]=mapped_column(Text); decisao:Mapped[Optional[str]]=mapped_column(Text)
class User(Base,T):
    __tablename__='usuarios'; id:Mapped[int]=mapped_column(primary_key=True); username:Mapped[str]=mapped_column(String(120),unique=True); display_name:Mapped[str]=mapped_column(String(160)); role:Mapped[str]=mapped_column(String(40)); active:Mapped[bool]=mapped_column(Boolean,default=True); password_hash:Mapped[Optional[str]]=mapped_column(String(128))
class AuditLog(Base):
    __tablename__='logs'; id:Mapped[int]=mapped_column(primary_key=True); timestamp:Mapped[datetime]=mapped_column(DateTime,default=utcnow); username:Mapped[Optional[str]]=mapped_column(String(120)); action:Mapped[str]=mapped_column(String(160)); entity:Mapped[Optional[str]]=mapped_column(String(120)); entity_id:Mapped[Optional[str]]=mapped_column(String(80)); cycle_code:Mapped[Optional[str]]=mapped_column(String(20)); grr:Mapped[Optional[str]]=mapped_column(String(20)); old_value:Mapped[Optional[str]]=mapped_column(Text); new_value:Mapped[Optional[str]]=mapped_column(Text); reason:Mapped[Optional[str]]=mapped_column(Text); code_version:Mapped[Optional[str]]=mapped_column(String(50)); rule_version:Mapped[Optional[str]]=mapped_column(String(50))
class Execution(Base):
    __tablename__='execucoes'; id:Mapped[int]=mapped_column(primary_key=True); started_at:Mapped[datetime]=mapped_column(DateTime,default=utcnow); finished_at:Mapped[Optional[datetime]]=mapped_column(DateTime); cycle_code:Mapped[Optional[str]]=mapped_column(String(20)); module:Mapped[str]=mapped_column(String(100)); status:Mapped[str]=mapped_column(String(40)); details:Mapped[Optional[str]]=mapped_column(Text)
class ImportedFile(Base):
    __tablename__='arquivos_importados'; id:Mapped[int]=mapped_column(primary_key=True); filename:Mapped[str]=mapped_column(String(240)); source:Mapped[str]=mapped_column(String(120)); sha256:Mapped[str]=mapped_column(String(64)); imported_at:Mapped[datetime]=mapped_column(DateTime,default=utcnow); username:Mapped[Optional[str]]=mapped_column(String(120)); cycle_code:Mapped[Optional[str]]=mapped_column(String(20)); row_count:Mapped[Optional[int]]=mapped_column(Integer); unique_grr:Mapped[Optional[int]]=mapped_column(Integer); schema_name:Mapped[Optional[str]]=mapped_column(String(120)); validation_status:Mapped[str]=mapped_column(String(60))
