[server]
headless = true
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
toolbarMode = "minimal"

[theme]
base = "light"
